/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package methoden;

/**
 *
 * @author moerli
 */
public class FrameTaschenrechner extends javax.swing.JFrame {

    /**
     * Creates new form FrameTaschenrechner
     */
    public FrameTaschenrechner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbplus = new javax.swing.JRadioButton();
        rbminus = new javax.swing.JRadioButton();
        rbdurch = new javax.swing.JRadioButton();
        rbmal = new javax.swing.JRadioButton();
        rbmodulo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        tfZahl1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfZahl2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblErgebnis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbplus);
        rbplus.setText("+");

        buttonGroup1.add(rbminus);
        rbminus.setText("-");

        buttonGroup1.add(rbdurch);
        rbdurch.setText("/");

        buttonGroup1.add(rbmal);
        rbmal.setText("*");

        buttonGroup1.add(rbmodulo);
        rbmodulo.setText("%");

        jLabel1.setText("Zahl1");

        tfZahl1.setText("10");
        tfZahl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfZahl1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Zahl2");

        tfZahl2.setText("20");

        jButton1.setText("Rechne");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblErgebnis.setText("Gleichnung");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblErgebnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfZahl1)
                                    .addComponent(tfZahl2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbmal)
                            .addComponent(rbdurch)
                            .addComponent(rbmodulo)
                            .addComponent(rbminus)
                            .addComponent(rbplus))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfZahl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfZahl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(rbmal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbdurch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbmodulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErgebnis)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ergebnis = "";
        try {
           int zahl1 = Integer.parseInt(tfZahl1.getText());
           int zahl2 = Integer.parseInt(tfZahl2.getText());
           if (rbplus.isSelected()) {
               ergebnis = zahl1+" + "+zahl2+" = "+Methoden.addiere(zahl1, zahl2);
           } else if (rbminus.isSelected()) {
               ergebnis = zahl1+" - "+zahl2+" = "+Methoden.subtrahiere(zahl1, zahl2);           
           } else if (rbmal.isSelected()) {
               ergebnis = zahl1+" * "+zahl2+" = "+Methoden.multipliziere(zahl1, zahl2);           
           } else if (rbdurch.isSelected()) {
               if (zahl2!=0) {
                   ergebnis = zahl1+" / "+zahl2+" = "+Methoden.dividiere(zahl1, zahl2); 
               } else {
                   ergebnis = "Division mit Null!";
               }
           } else if (rbmodulo.isSelected()) {
               if (zahl2!=0) {
                   ergebnis = zahl1+" % "+zahl2+" = "+Methoden.modulo(zahl1, zahl2);           
               } else {
                   ergebnis = "Division mit Null!";
               }
           }
       } 
       catch (Exception e) {
           ergebnis = "Mindestens eine der Zahlen ist falsch.";
       }
       lblErgebnis.setText(ergebnis);      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfZahl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfZahl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZahl1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTaschenrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTaschenrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTaschenrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTaschenrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTaschenrechner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblErgebnis;
    private javax.swing.JRadioButton rbdurch;
    private javax.swing.JRadioButton rbmal;
    private javax.swing.JRadioButton rbminus;
    private javax.swing.JRadioButton rbmodulo;
    private javax.swing.JRadioButton rbplus;
    private javax.swing.JTextField tfZahl1;
    private javax.swing.JTextField tfZahl2;
    // End of variables declaration//GEN-END:variables
}
